version: "1.0"
projectName: SIQA_APSA_gitProjectProject
runtimes:
- runtimeAlias: apsacrtpv
  assets:
  - name: APSA_Test
    type: DAF
- runtimeAlias: Cloud Runtime
  assets:
  - name: APSAClientApp
    type: DAF
  - name: APSAClientAppInternal
    type: DAF
